travis:
  secure:
    BINSTAR_TOKEN: ma67Kf6f5y99k4pF2hjX9GeGOq4LaR5pIj50BdYyi3cslFClUIypnHMMuT/NOG3pFRhLdxi1BxCXSpab+n4sIkS/JuD5o/AwQZf+aiLd5C9b9Gb4YIFyzp5prPCAVFgfaI/Q9Fp15WMcb/D89myTeORiCzoYeuKEPhh4JNRbiUwxjswHMgLORf+KuAuqoT+h+EF0sgN9ymEs+XTv2V8+Su7Me7M6K/BIk8fpF4ijnpp4U7DBF/j/HJ1uB9l+MF+xEaf3dVhPPVjZza2NgPoAIQ7bla1h3tjdclsUUBengk4YSN0mHOoJ4ky3trf6MPPWBM13ilgDhrdXrOAtFKRgg4I01+1POemkokRFhV0eT4JrS65wDQCKdqnea2bl4I212DrXP+9JOE3p0lIYpGYeGCkq2v2lw7qPQC0ozHys9wIC1wVCe3zDslmWLXPYNS1nw8wfe5P3i0enDO3weiNHfiYbCQ4yHwCkKap7bn81/enGr4NXa6fbgrbhMfQ8sLBiSvZzPe7WVw8K7nwBuiTE0+VEum7St4Abq+VxGmAfjPn3FAGr+MHCufSTlnFgHEX3ejSjbsyC/nvqOcvELiu6SfjSHrNVgw0kPWPdQDCCbzNze0PPc1jDxWayt2xn+R5/KdHlvkv2Y4wgEF6vGMRPaSRN4HZRly4CsTgQqdXvZEs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
